SET MODE MYSQL;
CREATE TABLE user1 (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(id)
);
truncate TABLE `user1`;

SET MODE MYSQL;
CREATE TABLE user2 (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(id)
);
truncate TABLE `user2`;